# fly.toml app configuration file generated for ccc-frontend on 2023-08-21T15:35:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ccc-frontend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
