stages:
  - build
  - deploy_frontend
  - deploy_backend

build-job:
  stage: build
  image: node:current-bullseye-slim
  script:
    - cd frontend
    - npm install
    - npm run build

deploy_frontend-job:
  stage: deploy_frontend
  image: docker:stable
  variables:
    FLY_API_TOKEN: $FLY_API_TOKEN_FRONTEND
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -L https://fly.io/install.sh | sh
    - cd frontend
    - export FLY_API_TOKEN=$FLY_API_TOKEN_FRONTEND
  script:
    - /root/.fly/bin/flyctl deploy

deploy_backend-job:
  stage: deploy_backend
  image: docker:stable
  variables:
    FLY_API_TOKEN: $FLY_API_TOKEN_BACKEND
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -L https://fly.io/install.sh | sh
    - cd backend
    - export FLY_API_TOKEN=$FLY_API_TOKEN_BACKEND
  script:
    - /root/.fly/bin/flyctl deploy


