stages:
  - deploy_frontend
  - deploy_backend

deploy_frontend:
  stage: deploy_frontend
  image: node:current-bullseye-slim
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"
  script:
    - cd frontend
    - flyctl deploy

deploy_backend:
  stage: deploy_backend
  image: python:3.8 # Choose an image with Python and necessary tools
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"
  script:
    - cd backend
    - flyctl deploy

# Add other stages and jobs as needed for your pipeline



