version: '3.8'
services:
  frontend:
    image: node:current-bullseye-slim
    container_name: vite-react
    entrypoint: ./app/entrypoint.sh
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    volumes:
        - type: bind
          source: ./frontend
          target: /app
    depends_on:
      - backend
    env_file:
      - .env
  backend:
    build: ./backend
    stdin_open: true
    tty: true
    ports:
      - "7007:7007"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    env_file:
      - .env
  postgres:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
