# Generated by Django 4.2.4 on 2023-09-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('document', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat_with_your_data_api.document')),
            ],
        ),
    ]
