# Generated by Django 4.2.4 on 2023-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0004_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
