# Generated by Django 4.2.4 on 2023-10-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_with_your_data_api", "0005_document_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lang",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
