# Generated by Django 4.2.4 on 2023-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0006_alter_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fileSize',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
