# Generated by Django 4.2.4 on 2023-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0007_document_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='doc_index',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
