# Generated by Django 5.0.2 on 2024-02-19 14:14

import chat_with_your_data_api.room_settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_with_your_data_api", "0009_user_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="settings",
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Room", max_length=255)),
                (
                    "anonymizeCompleteContext",
                    models.BooleanField(default=True, verbose_name="Anonymize Switch"),
                ),
                (
                    "prompt",
                    models.TextField(
                        default="Beantworte die folgende Frage ausschließlich mit folgenden Informationen:"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settings",
                    models.JSONField(
                        default=chat_with_your_data_api.room_settings.RoomSettings.to_dict
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_with_your_data_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roomID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_with_your_data_api.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnonymizeEntitie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymized", models.CharField(max_length=255)),
                ("deanonymized", models.CharField(max_length=255, unique=True)),
                ("entityType", models.CharField(max_length=255)),
                (
                    "roomID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_with_your_data_api.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_with_your_data_api.document",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_with_your_data_api.room",
                    ),
                ),
            ],
        ),
    ]
