# Generated by Django 5.0.2 on 2024-02-21 14:09

import chat_with_your_data_api.room_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_with_your_data_api",
            "0010_remove_user_settings_room_contextentry_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="prompt",
        ),
        migrations.AlterField(
            model_name="room",
            name="settings",
            field=models.JSONField(
                default=chat_with_your_data_api.room_settings.RoomSettings.to_dict
            ),
        ),
    ]
