# Generated by Django 5.0.2 on 2024-03-09 21:24

import chat_with_your_data_api.room_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_with_your_data_api",
            "0013_alter_anonymizeentitie_deanonymized_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="settings",
            field=models.JSONField(
                default=chat_with_your_data_api.room_settings.RoomSettings.to_dict
            ),
        ),
    ]
