# Generated by Django 4.2.4 on 2024-01-24 18:29

import chat_with_your_data_api.user_settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0013_alter_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('roomID', models.CharField(max_length=255, unique=True)),
                ('roomName', models.CharField(max_length=255)),
                ('anonymizeCompleteContext', models.BooleanField(default=True, verbose_name='Anonymize Switch')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.user_settings.UserSettings.to_dict),
        ),
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_your_data_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizeEntitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_your_data_api.room')),
            ],
        ),
    ]
