# Generated by Django 4.2.4 on 2024-01-24 19:00

import chat_with_your_data_api.user_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0016_alter_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(default='Room', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.user_settings.UserSettings.to_dict),
        ),
    ]
