# Generated by Django 5.0.9 on 2025-02-04 17:33

import chat_with_your_data_api.room_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0018_document_uploadedat_alter_room_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='headings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.room_settings.RoomSettings.to_dict),
        ),
    ]
