# Generated by Django 4.2.4 on 2024-01-24 20:08

import chat_with_your_data_api.user_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0018_alter_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='prompt',
            field=models.TextField(default='Beantworte die folgende Frage ausschließlich mit folgenden Informationen:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.user_settings.UserSettings.to_dict),
        ),
    ]
