# Generated by Django 4.2.4 on 2024-02-05 19:33

import chat_with_your_data_api.user_settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0019_room_prompt_alter_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.user_settings.UserSettings.to_dict),
        ),
    ]
