# Generated by Django 5.0.13 on 2025-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0019_document_headings_alter_room_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
