# Generated by Django 5.0.13 on 2025-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0020_alter_room_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizeentitie',
            name='anonymized',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='anonymizeentitie',
            name='deanonymized',
            field=models.CharField(max_length=1024),
        ),
    ]
