# Generated by Django 5.0.14 on 2025-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0021_alter_anonymizeentitie_anonymized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextentry',
            name='anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
