# Generated by Django 4.2.4 on 2024-02-05 19:54

import chat_with_your_data_api.user_settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0021_contextentry_created_at_alter_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.user_settings.UserSettings.to_dict),
        ),
        migrations.CreateModel(
            name='RoomDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_your_data_api.document')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_with_your_data_api.room')),
            ],
        ),
    ]
