# Generated by Django 5.0.14 on 2025-09-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0022_contextentry_anonymized'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anonymizeentitie',
            unique_together={('anonymized', 'deanonymized', 'roomID')},
        ),
    ]
