# Generated by Django 5.0.9 on 2025-02-17 09:01

import chat_with_your_data_api.room_settings
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0029_alter_room_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.room_settings.RoomSettings.to_dict),
        ),
    ]
