# Generated by Django 5.0.9 on 2025-02-17 09:16

import chat_with_your_data_api.room_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0030_user_last_reset_date_alter_room_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='settings',
            field=models.JSONField(default=chat_with_your_data_api.room_settings.RoomSettings.to_dict),
        ),
    ]
