# Generated by Django 5.0.13 on 2025-05-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0021_alter_anonymizeentitie_anonymized_and_more'),
        ('chat_with_your_data_api', '0032_alter_room_settings'),
    ]

    operations = [
    ]
