# Generated by Django 5.0.13 on 2025-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_your_data_api', '0033_merge_20250508_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
