name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest  
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Harbor Hub
        uses: docker/login-action@v1
        with:
          registry: harbor.enclaive.cloud
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend 
          file: ./frontend/Dockerfile
          push: true  
          tags: harbor.enclaive.cloud/garnet/frontend:latest
          no-cache: true
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_JWT_ISSUER=${{ secrets.VITE_JWT_ISSUER }}
            VITE_JWT_AUDIENCE=${{ secrets.VITE_JWT_AUDIENCE }}

  free-disk-space-build-docker:
      needs: build-and-push-frontend
      runs-on: ubuntu-latest
      steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
  build-and-push-backend:
    needs: free-disk-space-build-docker
    runs-on: ubuntu-latest  
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Harbor Hub
        uses: docker/login-action@v1
        with:
          registry: harbor.enclaive.cloud
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend 
          file: ./backend/Dockerfile
          push: true  
          tags: harbor.enclaive.cloud/garnet/backend:latest
          no-cache: true
  deploy:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            export DB_USER=${{ secrets.DB_USER }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export SECRET_KEY='${{ secrets.SECRET_KEY }}'
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export QDRANT_URL=${{ secrets.QDRANT_URL }}
            export QDRANT_SECRET=${{ secrets.QDRANT_SECRET }}
            export SPACY_NLP_MODEL=${{ secrets.SPACY_NLP_MODEL }}
            export TRANSFORMER_MODEL=${{ secrets.TRANSFORMER_MODEL }}
            export OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}
            export DOCKER_USERNAME=${{ secrets.HARBOR_USERNAME }}
            export DEBUG=${{ secrets.DEBUG }}
            export JWT_ISSUER=${{ secrets.JWT_ISSUER }}
            export JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
            docker compose pull
            docker compose up -d
	    docker exec -it backend cd /chat_with_your_data && python manage.py makemigrations
            docker exec -it backend cd /chat_with_your_data && python manage.py migrate
	    docker exec -it backend cd /chat_with_your_data && python manage.py create_demo_users
