name: CI/CD Workflow

on:
  workflow_dispatch:

env:
  IMAGE_PREFIX: ${{ secrets.HARBOR_REGISTRY }}/garnet

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest  
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}
      
      - name: Extract metadata (tags, labels) for Frontend Docker Image
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}/frontend


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend 
          file: ./frontend/Dockerfile
          push: true  
          tags: ${{ env.IMAGE_PREFIX }}/frontend:latest
          labels: ${{ steps.meta_backend.outputs.labels }}
          no-cache: true
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.EXP_VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.EXP_VITE_AUTH0_CLIENT_ID }}
            VITE_JWT_ISSUER=${{ secrets.EXP_VITE_JWT_ISSUER }}
            VITE_JWT_AUDIENCE=${{ secrets.EXP_VITE_JWT_AUDIENCE }}

  free-disk-space-build-docker:
      needs: build-and-push-frontend
      runs-on: ubuntu-latest
      steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
  build-and-push-backend:
    needs: free-disk-space-build-docker
    runs-on: ubuntu-latest  
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}
      
      - name: Extract metadata (tags, labels) for Frontend Docker Image
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}/backend


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend 
          file: ./backend/Dockerfile
          push: true  
          tags: ${{ env.IMAGE_PREFIX }}/backend:latest
          labels: ${{ steps.meta_backend.outputs.labels }}
          no-cache: true
  deploy:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Upload docker-compose.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EXP_SERVER_HOST }}
          username: ${{ secrets.EXP_SERVER_USER }}
          password: ${{ secrets.EXP_SERVER_SSH_PASSWORD }}
          source: "docker-compose-prod.yml"
          target: "${{ secrets.EXP_REMOTE_APP_PATH }}/"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EXP_SERVER_HOST }}
          username: ${{ secrets.EXP_SERVER_USER }}
          password: ${{ secrets.EXP_SERVER_SSH_PASSWORD }}
          script: |
            mv "${{ secrets.EXP_REMOTE_APP_PATH }}/docker-compose-prod.yml" "${{ secrets.EXP_REMOTE_APP_PATH }}/docker-compose.yml"
            export DB_USER=${{ secrets.DB_USER }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export SECRET_KEY='${{ secrets.SECRET_KEY }}'
            export DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
            export QDRANT_URL=${{ secrets.EXP_QDRANT_URL }}
            export QDRANT_SECRET=${{ secrets.EXP_QDRANT_SECRET }}
            export SPACY_NLP_MODEL=${{ secrets.SPACY_NLP_MODEL }}
            export TRANSFORMER_MODEL=${{ secrets.TRANSFORMER_MODEL }}
            export OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}
            export DOCKER_IMAGE_PREFIX=${{ env.IMAGE_PREFIX }}
            export DEBUG=${{ secrets.DEBUG }}
            export JWT_ISSUER=${{ secrets.EXP_JWT_ISSUER }}
            export JWT_AUDIENCE=${{ secrets.EXP_JWT_AUDIENCE }}
            export VITE_AUTH0_DOMAIN: ${{ secrets.EXP_VITE_AUTH0_DOMAIN }}
            export VITE_AUTH0_CLIENT_ID: ${{ secrets.EXP_VITE_AUTH0_CLIENT_ID }}
            export VITE_JWT_AUDIENCE: ${{ secrets.EXP_VITE_JWT_AUDIENCE }}
            export VITE_JWT_ISSUER: ${{ secrets.EXP_VITE_JWT_ISSUER }}
            
            echo "${{ secrets.HARBOR_SECRET }}" | docker login ${{ secrets.HARBOR_REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
            
            docker compose pull
            docker compose up -d
          command_timeout: 25m
