name: Experimental Deployment

on:
  workflow_dispatch:

env:
  SERVER_HOST: ${{ secrets.EXP_SERVER_HOST }}
  SERVER_USER: ${{ secrets.EXP_SERVER_USER }}
  SERVER_SSH_PASSWORD: ${{ secrets.EXP_SERVER_SSH_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EXP_SERVER_HOST }}
          username: ${{ secrets.EXP_SERVER_USER }}
          password: ${{ secrets.EXP_SERVER_SSH_PASSWORD }}
          script: |
            export DB_USER=${{ secrets.DB_USER }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export SECRET_KEY='${{ secrets.SECRET_KEY }}'
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export QDRANT_URL=${{ secrets.EXP_QDRANT_URL }}
            export QDRANT_SECRET=${{ secrets.EXP_QDRANT_SECRET }}
            export SPACY_NLP_MODEL=${{ secrets.SPACY_NLP_MODEL }}
            export TRANSFORMER_MODEL=${{ secrets.TRANSFORMER_MODEL }}
            export OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}
            export DOCKER_USERNAME=${{ secrets.EXP_DOCKER_USERNAME }}
            export DEBUG=${{ secrets.DEBUG }}
            export JWT_ISSUER=${{ secrets.EXP_JWT_ISSUER }}
            export JWT_AUDIENCE=${{ secrets.EXP_JWT_AUDIENCE }}
            docker compose pull
            docker compose up -d
          command_timeout: 25m
